site_name: FAQ pour les agents du Parc national du Mercantour
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  logo: img/logo_embleme_pnm_quadri_vert.jpg
    #    - toc.integrate
  language: fr
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Mode Sombre
      primary: light blue
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Mode Clair
      primary: light blue
      accent: purple

plugins:
  - search


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
 # - pymdownx.emoji:
 #     emoji_index: !!python/name:materialx.emoji.twemoji
 #     emoji_generator: !!python/name:materialx.emoji.to_svg

# exclude_docs: |



extra_css:
  - stylesheets/extra.css


# copyright: |
#  &copy; 2023 <a href="https://github.com/james-willett"  target="_blank" rel="noopener">James Willett</a>